-- AMS Skunk Telemetry - base schema (Fase 2)

create table if not exists public.drivers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique,
  display_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid references public.drivers(id) on delete set null,
  simulator text not null,
  track text not null,
  car text not null,
  session_type text,
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.laps (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  lap_number integer not null,
  lap_time_ms integer,
  sector_1_ms integer,
  sector_2_ms integer,
  sector_3_ms integer,
  valid boolean not null default true,
  fuel_l numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.live_sessions (
  id uuid primary key default gen_random_uuid(),
  simulator text not null,
  track text not null,
  car text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.live_drivers (
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  driver_key text not null,
  display_name text not null,
  position integer,
  class_position integer,
  lap integer,
  last_lap_ms integer,
  best_lap_ms integer,
  speed_kph numeric,
  rpm integer,
  gear integer,
  throttle numeric,
  brake numeric,
  steering numeric,
  fuel_l numeric,
  track_position numeric,
  updated_at timestamptz not null default now(),
  primary key(session_id, driver_key)
);
